In [4]:
#Q1
pip install numpy

     |████████████████████████████████| 15.4 MB 2.1 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [39]:
#Q2
np.version.version

'1.20.3'

In [33]:
#Q3 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
#Q4 
vecNull = np.zeros(10)
vecNull[4] = 1
vecNull

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [46]:
#Q5
z = np.arange(10, 51)
zReverse = np.flipud(z)
zReverse

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

In [47]:
#Q7
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [135]:
#Q8
matrix =  np.identity(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
#Q9
np.random.random(size=(3, 3, 3))

array([[[0.17978957, 0.92586004, 0.88704745],
        [0.35277788, 0.38667952, 0.64246678],
        [0.11150304, 0.26378273, 0.36128199]],

       [[0.76686801, 0.89001455, 0.78539155],
        [0.52764004, 0.11527537, 0.51164342],
        [0.25866183, 0.23902961, 0.925887  ]],

       [[0.94317767, 0.62951914, 0.06808526],
        [0.20281375, 0.13692126, 0.50074137],
        [0.10242326, 0.90564353, 0.93896983]]])

In [64]:
#Q10
matrice = np.random.random(size=(10, 10))
print(matrice.min())
print(matrice.max())

0.022523821479860984
0.9987742422280108


In [87]:
#Q11
np.diag([1,2,3,4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [61]:
#Q12 
liste = np.random.random(5)
liste.sum()

3.3492334227682043

In [72]:
#Q13
list = np.arange(1,6)
np.average(list)


3.0

In [76]:
#Q14
l = [x for x in np.arange(11)]
print(len(l))

11


In [143]:
#Q15
#print([x for x in np.random.random(10) if x not in [0, 1]])
# random = np.random.rand(10)
random = np.linspace(0,1,10, endpoint=False)[1:]
print(random)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [144]:
#Q16
arrA = np.random.random(5)
arrB = np.random.random(5)
comparison = arrA == arrB
equal_arrays = comparison.all()
print(equal_arrays)

False


In [145]:
#Q17
random = np.random.random(10).astype(np.float32)
print(random)
random = random.astype(np.int32)
print(random)

[0.14494014 0.03391254 0.13115665 0.67563885 0.8182863  0.22059491
 0.31921104 0.6617515  0.1221448  0.67887115]
[0 0 0 0 0 0 0 0 0 0]


In [154]:
#Q18
tab = [x for x in range(10)];tab

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [165]:
def moy(arr: list) -> float :
    """fonction renvoyant la moyenne"""
    result = 0
    for e in arr:
        result += e
    result = result/ len(arr)
    return result

In [167]:
moy(tab) == np.mean(tab)

True

In [162]:
#Q19
matrice = np.arange(0, 9).reshape((3, 3))
print(matrice)
mart2 = np.transpose(matrice)
print(mart2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
