In [4]:
pip install numpy

     |████████████████████████████████| 15.4 MB 2.1 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [39]:
np.version.version

'1.20.3'

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
vecNull = np.zeros(10)
vecNull[4] = 1
vecNull

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [46]:
z = np.arange(10, 51)
zReverse = np.flipud(z)
zReverse

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])